version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o bin cmd/addi-server/main.go

    run:
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run cmd/addi-server/main.go

    swagger.gen:
        desc: Generate Go code
        cmds:
        - swagger generate server -f swagger.json -A addi

    swagger.validate:
        desc: Validate swagger
        cmds:
        - swagger validate swagger.json

    swagger.doc:
        desc: Doc for swagger
        cmds:
        - swagger serve --no-open --port=80 ./swagger.json